apiVersion: apps/v1
kind: Deployment
metadata:
  name: red
  labels:
    app: myapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp

  template:
    metadata:
      name: nginx-deploy
      labels:
        app: myapp
    spec:
      containers:
        - name: nginx-deploy
          image: nginx
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node-role.kubernetes.io/master
                    operator: Exists
