apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-frontend
  labels:
    app: myapp
    type: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp

  template:
    metadata:
      name: myapp-prod
      labels:
        app: myapp
    spec:
      containers:
        - name: httpd-alpine
          image: httpd:2.4-alpine
