apiVersion: batch/v1
metadata:
  name: throw-dice-job
kind: Job
spec:
  completions: 3
  backoffLimit: 25
  template:
    spec:
      containers:
        - image: kodekloud/throw-dice
          name: throw-dice
      restartPolicy: Never
