apiVersion: v1

kind: Pod

metadata:
  name: bee

spec:
  containers:
    - name: bee
      image: nginx
      resources:
        limits:
          memory: 10Mi
          cpu: 1
        requests:
          memory: 5Mi
          cpu: 1
