apiVersion: v1

kind: Pod

metadata:
  name: simple-webapp-1

spec:
  containers:
    - name: simple-webapp-1
      image: kodekloud/webapp-delayed-start
      livenessProbe:
        initialDelaySeconds: 80
        periodSeconds: 1
        httpGet:
          path: /live
          port: 8080
