apiVersion: v1

kind: Pod

metadata:
  name: bee

spec:
  containers:
    - name: bee
      image: nginx
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: size
                operator: In
                values:
                  - Large
#Operators In (values array), NotIn(values array), Exists(matchea con key)
