apiVersion: v1

kind: Pod

metadata:
  name: simple-webapp-2

spec:
  containers:
    - name: simple-webapp-2
      image: kodekloud/webapp-delayed-start
      readinessProbe:
        initialDelaySeconds: 80
        httpGet:
          path: /ready
          port: 8080
